# Generated by Django 5.0.6 on 2024-08-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
